In [1]:
from sklearn.cluster import KMeans
import numpy as np

In [2]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])

In [11]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

In [8]:
import random

random.seed(10)
for i in range(10):
    print(random.random())

0.5714025946899135
0.4288890546751146
0.5780913011344704
0.20609823213950174
0.81332125135732
0.8235888725334455
0.6534725339011758
0.16022955651881965
0.5206693596399246
0.32777281162209315


In [9]:
random.seed(10)
for i in range(10):
    print(random.random())

0.5714025946899135
0.4288890546751146
0.5780913011344704
0.20609823213950174
0.81332125135732
0.8235888725334455
0.6534725339011758
0.16022955651881965
0.5206693596399246
0.32777281162209315


In [12]:
kmeans.labels_

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [13]:
kmeans.predict([[0, 0], [12, 3]])

array([1, 0], dtype=int32)

In [14]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])